on:
  push:
    branches:
      - main
jobs:
  tsc:
    name: Compile typescript
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: install node v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: install dependencies
      run: |
        npm install
        cd ./src
        npm install
    - name: tsc
      run: tsc
    - name: Upload the build folder
      uses: actions/upload-artifact@master
      with:
        name: build-artifact
        path: build
    - name: log
      run: tree
  get-lambda-files-names:
    name: Parse the lambdas folders names
    runs-on: ubuntu-latest
    needs: tsc
    outputs:
      lambdaArray: ${{ steps.getLambdas.outputs.lambdas }}
    steps:
      - name: Download the build folder
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: build
      - name: Get functions filenames
        id: getLambdas
        run: |
          lambdas=$(tree -J | jq '.[0].contents | map(select(.name == "build" and .type == "directory")) | .[0].contents | try map(select(.name == "functions" and .type == "directory")) catch [] | .[0].contents | try map(select(.type == "directory")) catch [] | map(.name)')
          echo ${lambdas}
          echo ::set-output name=lambdas::${lambdas}
      - name: log
        run: tree
  lambdas:
    runs-on: ubuntu-latest
    needs: get-lambda-files-names
    strategy:
      matrix:
        lambda: ${{ fromJSON(needs.get-lambda-files-names.outputs.lambdaArray) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Download the build folder
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: build
      - name: Debug log tree
        run: tree
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - run: |
          cd ./build/functions/${{matrix.lambda}}
          zip -r ../../../${{matrix.lambda}}.zip .
          cd ../../../
      - run: aws lambda update-function-code --function-name=${{matrix.lambda}} --zip-file=fileb://${{matrix.lambda}}.zip
  layer:
    name: Upload packages to AWS layer
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: tsc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install the dependencies
        run: |
          cd ./src
          npm i
      - name: Download the build folder
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: build
      - name: Move 'utils' to 'node_modules'
        run: |
          mv build/utils ./src/node_modules
      - name: Move 'node_modules' to 'nodejs' folder
        run: |
          cd ./src
          mkdir nodejs
          mv node_modules ./nodejs
      - name: Zip the packages
        run: |
          cd ./src
          zip -r ../layer.zip ./nodejs
      - name: No packages found
        if: ${{failure()}}
        run: echo "No packages found"
      - name: log
        run: tree -L 2
      - name: Upload the zip file to AWS layer
        run: aws lambda publish-layer-version --layer-name goLayer --zip-file fileb://layer.zip --compatible-runtimes nodejs20.x --compatible-architectures x86_64
      